export const ADD_CITY = "ADD_CITY";
export const REMOVE_CITY = "REMOVE_CITY";

export const REQUEST_API_DATA = "REQUEST_API_DATA";
export const RECEIVE_API_DATA = "RECEIVE_API_DATA";

export const GET_WEATHER_BY_ID_REQUEST ="GET_WEATHER_BY_ID_REQUEST";
export const GET_WEATHER_BY_ID_SUCCESS ="GET_WEATHER_BY_ID_SUCCESS";
export const GET_WEATHER_BY_ID_ERROR ="GET_WEATHER_BY_ID_ERROR";

export const GET_FORECAST_BY_ID_REQUEST = "GET_FORECAST_BY_ID_REQUEST";
export const GET_FORECAST_BY_ID_SUCCESS = "GET_FORECAST_BY_ID_SUCCESS";
export const GET_FORECAST_BY_ID_ERROR = "GET_FORECAST_BY_ID_ERROR";

export const GET_WEATHER_BY_GROUP_REQUEST ="GET_WEATHER_BY_GROUP_REQUEST";
export const GET_WEATHER_BY_GROUP_SUCCESS ="GET_WEATHER_BY_GROUP_SUCCESS";
export const GET_WEATHER_BY_GROUP_ERROR ="GET_WEATHER_BY_GROUP_ERROR";